### ISSUE TITLE
Always print filenames with error messages

### ISSUE THREAD

**Issue by mcandre** [markdrago/pgsanity#11]
I often use Unix `find` to send many `*.sql` files individually to pgsanity:

```
$ find lib -name "*.sql" -exec pgsanity {} \;
line 7: ERROR: syntax error at or near ":db"
line 7: ERROR: syntax error at or near ":db"
line 7: ERROR: syntax error at or near ":db"
```

When I do this, pgsanity neglects to show the filename, making it hard to tell which files have the syntax errors. Please always show the filename, no matter how many files a pgsanity process is checking.

As a workaround, I'm using `find lib -name "*.sql" \( -exec pgsanity {} \; -o -print \)`, but that prints the filenames after the warnings, rather than prefixing each line.

**Comment by markdrago** [comment]
Andrew,

Thanks for filing the issue.  The approach pgsanity takes is that it will print the filename if more than one filename is passed as a parameter.  One way to get that behavior right now is to change the way you're calling pgsanity.  Rather than using the -exec option with find, you could do this:

```
$ find lib -name "*.sql" | xargs pgsanity
```

That will lead to pgsanity being called with more than one filename and that will trigger pgsanity to print the filenames.  I'm not against adding a flag to pgsanity, grep uses -H, to always print the filename, but this workaround will get you the behavior you want right away.

**Comment by mcandre** [comment]
Thanks for the xargs tip, that's a good idea.
